### ISSUE TITLE
Strange crash report

### ISSUE THREAD

**Issue by mjtb49** [mjtb49/StrongholdTrainer#32]
Received the following crash report during testing today, unclear whether related to this mod. 

---- Minecraft Crash Report ----
// You're mean.

Time: 6/20/21, 2:24 PM
Description: Exception generating new chunk

java.util.ConcurrentModificationException
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at net.minecraft.structure.StructureManager.getStructure(StructureManager.java:56)
	at net.minecraft.structure.StructureManager.getStructureOrBlank(StructureManager.java:45)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.structure.pool.SinglePoolElement.method_27233(SinglePoolElement.java:79)
	at net.minecraft.structure.pool.SinglePoolElement.getBoundingBox(SinglePoolElement.java:109)
	at net.minecraft.structure.pool.StructurePool.method_19310(StructurePool.java:74)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:496)
	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:459)
	at net.minecraft.structure.pool.StructurePool.getHighestY(StructurePool.java:74)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.method_19305(StructurePoolBasedGenerator.java:183)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:496)
	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:459)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.generatePiece(StructurePoolBasedGenerator.java:176)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.method_27232(StructurePoolBasedGenerator.java:106)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator.addPieces(StructurePoolBasedGenerator.java:70)
	at net.minecraft.structure.VillageGenerator.addPieces(VillageGenerator.java:25)
	at net.minecraft.world.gen.feature.VillageFeature$Start.init(VillageFeature.java:28)
	at net.minecraft.world.gen.feature.VillageFeature$Start.init(VillageFeature.java:23)
	at net.minecraft.world.gen.feature.StructureFeature.method_28657(StructureFeature.java:217)
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.method_28622(ConfiguredStructureFeature.java:29)
	at net.minecraft.world.gen.chunk.ChunkGenerator.method_28508(ChunkGenerator.java:253)
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator.java:245)
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus.java:181)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus.java:135)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage.java:539)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage.java:536)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem.java:43)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor.java:88)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor.java:132)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor.java:100)
	at java.base/java.util.concurrent.ForkJoinTask$RunnableExecuteAction.exec(ForkJoinTask.java:1426)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Server thread
Stacktrace:
	at java.base/java.util.HashMap.computeIfAbsent(HashMap.java:1134)
	at net.minecraft.structure.StructureManager.getStructure(StructureManager.java:56)
	at net.minecraft.structure.StructureManager.getStructureOrBlank(StructureManager.java:45)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.structure.pool.SinglePoolElement.method_27233(SinglePoolElement.java:79)
	at net.minecraft.structure.pool.SinglePoolElement.getBoundingBox(SinglePoolElement.java:109)
	at net.minecraft.structure.pool.StructurePool.method_19310(StructurePool.java:74)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:496)
	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:459)
	at net.minecraft.structure.pool.StructurePool.getHighestY(StructurePool.java:74)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.method_19305(StructurePoolBasedGenerator.java:183)
	at java.base/java.util.stream.ReferencePipeline$4$1.accept(ReferencePipeline.java:212)
	at java.base/java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1654)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:484)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
	at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.IntPipeline.reduce(IntPipeline.java:496)
	at java.base/java.util.stream.IntPipeline.max(IntPipeline.java:459)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.generatePiece(StructurePoolBasedGenerator.java:176)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator$StructurePoolGenerator.method_27232(StructurePoolBasedGenerator.java:106)
	at net.minecraft.structure.pool.StructurePoolBasedGenerator.addPieces(StructurePoolBasedGenerator.java:70)
	at net.minecraft.structure.VillageGenerator.addPieces(VillageGenerator.java:25)
	at net.minecraft.world.gen.feature.VillageFeature$Start.init(VillageFeature.java:28)
	at net.minecraft.world.gen.feature.VillageFeature$Start.init(VillageFeature.java:23)
	at net.minecraft.world.gen.feature.StructureFeature.method_28657(StructureFeature.java:217)
	at net.minecraft.world.gen.feature.ConfiguredStructureFeature.method_28622(ConfiguredStructureFeature.java:29)
	at net.minecraft.world.gen.chunk.ChunkGenerator.method_28508(ChunkGenerator.java:253)
	at net.minecraft.world.gen.chunk.ChunkGenerator.setStructureStarts(ChunkGenerator.java:245)
	at net.minecraft.world.chunk.ChunkStatus.method_16556(ChunkStatus.java:181)
	at net.minecraft.world.chunk.ChunkStatus.runGenerationTask(ChunkStatus.java:135)

-- Chunk to be generated --
Details:
	Location: 17143,4
	Position hash: 17179886327
	Generator: net.minecraft.world.gen.chunk.SurfaceChunkGenerator@78502805
Stacktrace:
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17225(ThreadedAnvilChunkStorage.java:539)
	at com.mojang.datafixers.util.Either$Left.map(Either.java:38)
	at net.minecraft.server.world.ThreadedAnvilChunkStorage.method_17224(ThreadedAnvilChunkStorage.java:536)
	at java.base/java.util.concurrent.CompletableFuture$UniCompose.tryFire(CompletableFuture.java:1072)
	at java.base/java.util.concurrent.CompletableFuture$Completion.run(CompletableFuture.java:478)
	at net.minecraft.server.world.ChunkTaskPrioritySystem.method_17634(ChunkTaskPrioritySystem.java:43)
	at net.minecraft.util.thread.TaskExecutor.runNext(TaskExecutor.java:88)
	at net.minecraft.util.thread.TaskExecutor.runWhile(TaskExecutor.java:132)
	at net.minecraft.util.thread.TaskExecutor.run(TaskExecutor.java:100)

-- Affected level --
Details:
	All players: 1 total; [ServerPlayerEntity['Player31'/60, l='ServerLevel[New World]', x=274428.75, y=32.00, z=4.30]]
	Chunk stats: ServerChunkCache: 2946
	Level dimension: minecraft:overworld
	Level spawn location: World: (48,64,-96), Chunk: (at 0,4,0 in 3,-6; contains blocks 48,0,-96 to 63,255,-81), Region: (0,-1; contains chunks 0,-32 to 31,-1, blocks 0,0,-512 to 511,255,-1)
	Level time: 202514 game time, 202514 day time
	Level name: New World
	Level game mode: Game mode: creative (ID 1). Hardcore: false. Cheats: true
	Level weather: Rain time: 48435 (now: false), thunder time: 90422 (now: false)
	Known server brands: fabric
	Level was modded: true
	Level storage version: 0x04ABD - Anvil
Stacktrace:
	at net.minecraft.server.MinecraftServer.tickWorlds(MinecraftServer.java:873)
	at net.minecraft.server.MinecraftServer.tick(MinecraftServer.java:808)
	at net.minecraft.server.integrated.IntegratedServer.tick(IntegratedServer.java:82)
	at net.minecraft.server.MinecraftServer.runServer(MinecraftServer.java:666)
	at net.minecraft.server.MinecraftServer.method_29739(MinecraftServer.java:226)
	at java.base/java.lang.Thread.run(Thread.java:834)

-- System Details --
Details:
	Minecraft Version: 1.16.1
	Minecraft Version ID: 1.16.1
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 11, Oracle Corporation
	Java VM Version: Java HotSpot(TM) 64-Bit Server VM (mixed mode), Oracle Corporation
	Memory: 119811904 bytes (114 MB) / 570425344 bytes (544 MB) up to 4265607168 bytes (4068 MB)
	CPUs: 8
	JVM Flags: 0 total; 
	Player Count: 1 / 8; [ServerPlayerEntity['Player31'/60, l='ServerLevel[New World]', x=274428.75, y=32.00, z=4.30]]
	Data Packs: vanilla
	Type: Integrated Server (map_client.txt)
	Is Modded: Definitely; Client brand changed to 'fabric'

**Comment by ScribbleTAS** [comment]
Well, for me I often had this issue... This came usually on multithreadding, often related to chunkloading, when a List is modified by 2 different threads at the same time... Thats as far as I understand it and it is probably related to the mod... Maybe something gets executed twice in a row, or saved on another thread?

**Comment by mjtb49** [comment]
It's not our fault

https://github.com/FabricMC/fabric/pull/1176

**Comment by mjtb49** [comment]
https://bugs.mojang.com/browse/MC-149777
